package is.cityreportsystem.model;

public enum ReportType {
	HEATING,WATER,ELECTRICITY,GARBAGE,PARKING,ROAD,SNOW,TRAFFIC,VIOLENCE,HEALTCARE,PEACE,FIRE,MIGRANTS,LIGHTS,TRAFFIC_ACCIDENT,BRIBE,COMPANY
}
