package is.cityreportsystem.model.enums;

public enum ReportType {
	GRIJANJE_HEATING,VODOVOD_WATER,STRUJA_ELECTRICITY,SMECE_GARBAGE,PARKIRANJE_PARKING,PUTEVI_ROAD,SNIJEG_SNOW,SAOBRACAJ_TRAFFIC,MIGRANTI_MIGRANTS,RASVJETA_LIGHTS,PRIVREDNICI_COMPANY
}
